#! /bin/sh
### BEGIN INIT INFO
# Provides:          locastyle
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Locastyle - Default Interface to Locaweb
### END INIT INFO

APP_PATH=/var/www/locastyle

NAME=locastyle-monitor
DESC=locastyle-monitor
GOD="bundle exec god"

set -e

case "$1" in
  start)
    echo -n "Starting $DESC:"
    if (cd $APP_PATH && $GOD -c $APP_PATH/god/web.god && $GOD start appserver)
    then
      echo "$NAME started"
    else
      echo "failed"
    fi
  ;;

  stop)
    echo -n "Stopping $DESC: "
    if (cd $APP_PATH && $GOD stop appserver && $GOD terminate)
    then
      echo "$NAME stopped."
    else
      echo "failed!"
    fi
  ;;

  restart)
    ${0} stop
    ${0} start
  ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 1
  ;;
esac

exit 0
