#!/bin/sh -e

APP_PATH="/var/www/locastyle"

case "$1" in

  configure)
    mkdir -p $APP_PATH/tmp
    mkdir -p $APP_PATH/log
    mkdir -p /var/log/locastyle

    chown locastyle:locastyle /var/log/locastyle
    chown -R locastyle:locastyle $APP_PATH
  ;;

esac

#DEBHELPER#

exit 0
