#!/bin/sh -e

APP_PATH="/var/www/locastyle"

case "$1" in

  configure)
    chown locastyle:locastyle /var/log/locastyle
    chown -R locastyle:locastyle $APP_PATH
    invoke-rc.d locastyle restart
  ;;

esac

#DEBHELPER#

exit 0
