#!/bin/sh -e

APP_PATH="/var/www/locastyle"

case "$1" in
  install|upgrade)
    id locastyle > /dev/null 2>&1 || adduser --home "/var/www/locastyle" --system locastyle --group

    mkdir -p $APP_PATH/tmp
    mkdir -p $APP_PATH/tmp/pids
    mkdir -p $APP_PATH/log
    mkdir -p /var/log/locastyle
  ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
